In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pmdarima as pm

from datetime import datetime, timedelta
import seaborn as sns

In [3]:
first_export = pd.read_csv("zasilka-TP4VGT9M89DDMFIM/export_all_ids_2020.csv/export_all_ids.csv", sep=";")

In [4]:
first_export.head()

      id            timestamp  hodnota
0  65915  2020-01-01 00:20:51  1313.53
1  65915  2020-01-01 01:20:47  1313.64
2  65915  2020-01-01 02:20:30  1313.91
3  65915  2020-01-01 03:20:20  1314.04
4  65915  2020-01-01 04:20:21  1314.15

In [5]:
first_export.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23646713 entries, 0 to 23646712
Data columns (total 3 columns):
 #   Column     Dtype
---  ------     -----
 0   id         int64
 1   timestamp  object
 2   hodnota    float64
dtypes: float64(1), int64(1), object(1)
memory usage: 541.2+ MB

In [6]:
first_export['id'].nunique()

4681

In [7]:
first_export.isna().values.sum()

2818

In [8]:
first_export[first_export.isna().any(axis=1)]

             id            timestamp  hodnota
4848234   71934  2020-05-28 10:39:22      NaN
4848235   71934  2020-05-28 10:40:32      NaN
4848236   71934  2020-05-28 10:41:42      NaN
4848237   71934  2020-05-28 10:42:23      NaN
4848238   71934  2020-05-28 10:45:30      NaN
...         ...                  ...      ...
16208682  85696  2020-10-16 09:14:49      NaN
16208683  85696  2020-10-16 10:14:50      NaN
16208684  85696  2020-10-16 11:14:51      NaN
16208685  85696  2020-10-16 11:18:26      NaN
16208686  85696  2020-10-16 11:19:42      NaN

[2818 rows x 3 columns]

In [9]:
first_export['id'].isna().values.sum()

0

In [10]:
split_dfs = {group_id: group_df for group_id, group_df in first_export.groupby('id')}

In [11]:
split_dfs[71934][split_dfs[71934].isna().any(axis=1)].head()

            id            timestamp  hodnota
4848234  71934  2020-05-28 10:39:22      NaN
4848235  71934  2020-05-28 10:40:32      NaN
4848236  71934  2020-05-28 10:41:42      NaN
4848237  71934  2020-05-28 10:42:23      NaN
4848238  71934  2020-05-28 10:45:30      NaN

In [17]:
def split_and_save_df(df: pd.DataFrame):
    split_dfs = {group_id: group_df for group_id, group_df in df.groupby('id')}
    
    first_df = list(split_dfs.values())[0]
    year = first_df["timestamp"].iloc[0].split("-")[0]
    print(year)
    
    for df_id, df_values in split_dfs.items():
        df_values.to_csv(f"split_data/{df_id}-{year}.csv")
    
split_and_save_df(first_export)

2020